export const ROLE_MODES = [
  {
    id: "buyer",
    title: "Buyer / Tenant",
    description: "Search verified properties, save favorites, and connect with sellers.",
  },
  {
    id: "owner",
    title: "Property Owner",
    description: "Post sale or rental listings with media, pricing, and amenities.",
  },
  {
    id: "agent",
    title: "Agent / Broker",
    description: "Manage multiple listings, premium boosts, and active leads.",
  },
  {
    id: "builder",
    title: "Builder / Developer",
    description: "Launch projects, manage inventory, and showcase unit availability.",
  },
  {
    id: "admin",
    title: "Admin",
    description: "Approve listings, verify users, monitor disputes, and track analytics.",
  },
];

export const CONSTRUCTION_SERVICES = [
  {
    id: "renovation",
    title: "Renovation & Interiors",
    description: "Design, budgeting, and trusted contractors for every home upgrade.",
  },
  {
    id: "project-launch",
    title: "Project Marketing",
    description: "Launch ready-to-sell inventory, virtual tours, and booking workflows.",
  },
  {
    id: "legal-support",
    title: "Legal & Documentation",
    description: "Title search, agreements, approvals and regulatory compliance support.",
  },
  {
    id: "tenant-services",
    title: "Tenant Services",
    description: "Rent collection, maintenance scheduling, and move-in welcome support.",
  },
];

export const HOME_LOAN_PARTNERS = [
  { name: "Nila Bank Home Loans", rate: 7.9 },
  { name: "Gulf Finance Partners", rate: 8.1 },
  { name: "Malabar Housing Credit", rate: 8.5 },
];

export const TENANT_UTILITIES = [
  "Rent payment reminders",
  "Maintenance request tracking",
  "Rental agreement templates",
  "Homeowner insurance guidance",
];

export const LEAD_STAGE_OPTIONS = [
  { value: "new", label: "New" },
  { value: "contacted", label: "Contacted" },
  { value: "site_visit", label: "Site Visit" },
  { value: "negotiation", label: "Negotiation" },
  { value: "token_paid", label: "Token Paid" },
  { value: "closed", label: "Closed" },
  { value: "lost", label: "Lost" },
];

export const LISTING_TYPE_OPTIONS = [
  "Apartment",
  "Flat",
  "Villa",
  "House",
  "Plot",
  "Land",
  "Commercial",
  "Office",
  "Shop",
  "Warehouse",
  "Farm land",
  "Studio",
];

export const TITLE_DEED_OPTIONS = [
  { value: "pending", label: "Pending" },
  { value: "verified", label: "Verified" },
  { value: "rejected", label: "Rejected" },
  { value: "not-applicable", label: "Not applicable" },
];

export const DEFAULT_LISTING_FORM = {
  postingType: "property", // "property" (selling) or "requirement" (buyer looking for)
  title: "",
  intent: "sale",
  priceLabel: "",
  location: "",
  locality: "",
  type: "Flat",
  bedrooms: "2",
  bathrooms: "2",
  furnishing: "Semi Furnished",
  areaSqft: "1200",
  carpetAreaSqft: "",
  builtUpAreaSqft: "",
  landSizeSqft: "",
  floorNumber: "",
  totalFloors: "",
  parkingSpots: "",
  propertyAgeYears: "",
  possession: "Ready to move",
  address: "",
  landmark: "",
  contactPhone: "",
  whatsappNumber: "",
  mapLocationLat: "",
  mapLocationLng: "",
  videoTourUrl: "",
  floorPlanUrl: "",
  brochureUrl: "",
  mapPreviewUrl: "",
  mediaGalleryInput: "",
  amenitiesInput: "",
  nearbySchoolKm: "",
  nearbyHospitalKm: "",
  nearbyMetroKm: "",
  readyToMove: true,
  underConstruction: false,
  reraNumber: "",
  titleDeedStatus: "pending",
  taxReceipt: false,
  buildingPermit: false,
  encumbranceCertificate: false,
  description: "",
  // Requirement-specific fields (shown when postingType === "requirement")
  maxBudget: "",
  minBudget: "",
  preferredLocations: "",
  mustHaveAmenities: "",
  moveInDate: "",
};

const buildSeedMedia = (image, video, floorPlan, brochure, mapPreview) => [
  { id: "m-1", type: "image", label: "Front view", url: image, order: 0 },
  ...(video ? [{ id: "m-2", type: "video", label: "Video tour", url: video, order: 1 }] : []),
  ...(floorPlan ? [{ id: "m-3", type: "floor-plan", label: "Floor plan", url: floorPlan, order: 2 }] : []),
  ...(brochure ? [{ id: "m-4", type: "brochure", label: "Brochure", url: brochure, order: 3 }] : []),
  ...(mapPreview ? [{ id: "m-5", type: "map", label: "Map preview", url: mapPreview, order: 4 }] : []),
];

export const REAL_ESTATE_SEED_PROPERTIES = [
  {
    id: "re-1",
    title: "Skyline Residency 3 BHK",
    price: "95 Lakhs",
    priceLabel: "95 Lakhs",
    priceValue: 95,
    area: "1650 sq ft",
    areaSqft: 1650,
    carpetAreaSqft: 1320,
    builtUpAreaSqft: 1650,
    landSizeSqft: null,
    location: "Kochi",
    locality: "Kakkanad",
    address: "Skyline Residency, Kakkanad, Kochi, Kerala",
    landmark: "Near SmartCity",
    mapLocationLat: 10.0159,
    mapLocationLng: 76.3419,
    mapPreviewUrl: "",
    type: "Flat",
    intent: "sale",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&h=800&fit=crop",
    mediaGallery: buildSeedMedia(
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&h=800&fit=crop",
      "https://samplelib.com/lib/preview/mp4/sample-5s.mp4",
      "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
      "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
      "https://maps.googleapis.com/maps/api/staticmap?center=10.0159,76.3419&zoom=13&size=600x300"
    ),
    videoTourUrl: "https://samplelib.com/lib/preview/mp4/sample-5s.mp4",
    floorPlanUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    brochureUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    bedrooms: 3,
    bathrooms: 3,
    floorNumber: 12,
    totalFloors: 18,
    parkingSpots: 2,
    propertyAgeYears: 2,
    furnishing: "Semi Furnished",
    amenities: ["Covered parking", "Clubhouse", "Security", "Power backup"],
    sellerName: "Amina Niyas",
    sellerRole: "Owner",
    listedBy: "Owner",
    verified: true,
    verificationStatus: "Verified",
    reraNumber: "K-RERA/PRJ/KOCHI/1024",
    titleDeedStatus: "verified",
    taxReceipt: true,
    buildingPermit: true,
    encumbranceCertificate: true,
    contactPhone: "+91 9876543210",
    whatsappNumber: "+91 9876543210",
    readyToMove: true,
    underConstruction: false,
    nearbySchoolKm: 1.3,
    nearbyHospitalKm: 2.1,
    nearbyMetroKm: 1.1,
    featured: true,
    postedOn: "2026-04-18",
    possession: "Ready to move",
    description:
      "A family-ready apartment near the IT corridor with metro access, strong resale demand, and community amenities.",
    mapLabel: "Kakkanad smart city corridor",
    rating: 4.8,
    reviewCount: 36,
    premiumPlan: "Featured Listing",
    mediaCount: 12,
    hasVideoTour: true,
    leads: [{ id: "lead-1", name: "Riyas", channel: "Chat", priority: "Hot", status: "new" }],
    visits: [],
    chatPreview: [{ from: "Amina Niyas", text: "Floor plan and legal summary are ready to share." }],
    reviews: [{ author: "Shahid", score: 5, comment: "Verified documents and fast site visit support." }],
    languageSupport: ["English", "Malayalam"],
    disputeCount: 0,
    status: "available",
  },
  {
    id: "re-2",
    title: "Smart Rental Studio",
    price: "28,000 / month",
    priceLabel: "28,000 / month",
    priceValue: 28,
    area: "640 sq ft",
    areaSqft: 640,
    carpetAreaSqft: 510,
    builtUpAreaSqft: 640,
    location: "Trivandrum",
    locality: "Technopark Phase 1",
    address: "Technopark Phase 1, Trivandrum, Kerala",
    type: "Studio",
    intent: "rent",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200&h=800&fit=crop",
    mediaGallery: buildSeedMedia(
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200&h=800&fit=crop",
      "",
      "",
      "",
      ""
    ),
    bedrooms: 1,
    bathrooms: 1,
    furnishing: "Furnished",
    amenities: ["Wi-Fi", "Lift", "Security", "Housekeeping access"],
    sellerName: "Rohit Menon",
    sellerRole: "Owner",
    listedBy: "Owner",
    verified: true,
    verificationStatus: "Verified",
    reraNumber: "",
    titleDeedStatus: "verified",
    taxReceipt: true,
    buildingPermit: true,
    encumbranceCertificate: false,
    readyToMove: true,
    underConstruction: false,
    nearbySchoolKm: 3.4,
    nearbyHospitalKm: 1.9,
    nearbyMetroKm: null,
    featured: false,
    postedOn: "2026-04-19",
    possession: "Immediate",
    description: "Compact and fully furnished studio for quick move-in professionals.",
    mapLabel: "Technopark rental cluster",
    rating: 4.4,
    reviewCount: 19,
    premiumPlan: "Starter",
    mediaCount: 9,
    hasVideoTour: false,
    leads: [{ id: "lead-2", name: "Devika", channel: "Call", priority: "Warm", status: "contacted" }],
    reviews: [{ author: "Arun", score: 4, comment: "Well-maintained and easy move-in process." }],
    languageSupport: ["English", "Malayalam", "Tamil"],
    disputeCount: 0,
    status: "available",
  },
];

export const SUBSCRIPTION_PLANS = [
  { id: "starter", name: "Starter", amountInr: 499, featuredCredits: 1, listingLimit: 1, durationDays: 30 },
  { id: "featured", name: "Featured", amountInr: 1499, featuredCredits: 5, listingLimit: 5, durationDays: 30 },
  { id: "agent-pro", name: "Agent Pro", amountInr: 2999, featuredCredits: 15, listingLimit: 999, durationDays: 30 },
  { id: "builder-pro", name: "Builder Pro", amountInr: 4999, featuredCredits: 35, listingLimit: 999, durationDays: 30 },
];

// ─── India Cities by State ────────────────────────────────────────────────────
export const INDIA_CITIES_BY_STATE = {
  Kerala: ["Kochi", "Trivandrum", "Kozhikode", "Thrissur", "Kannur", "Kollam", "Palakkad", "Malappuram", "Kottayam", "Alappuzha"],
  Maharashtra: ["Mumbai", "Pune", "Nagpur", "Nashik", "Aurangabad", "Thane", "Navi Mumbai", "Solapur", "Kolhapur", "Amravati"],
  Karnataka: ["Bangalore", "Mysore", "Hubli", "Mangalore", "Belgaum", "Gulbarga", "Davangere", "Bellary", "Shimoga", "Tumkur"],
  "Tamil Nadu": ["Chennai", "Coimbatore", "Madurai", "Tiruchirappalli", "Salem", "Tirunelveli", "Vellore", "Erode", "Tiruppur", "Dindigul"],
  "Delhi NCR": ["New Delhi", "Gurgaon", "Noida", "Faridabad", "Ghaziabad", "Greater Noida", "Dwarka", "Rohini", "Janakpuri"],
  Telangana: ["Hyderabad", "Warangal", "Nizamabad", "Khammam", "Karimnagar", "Ramagundam", "Secunderabad", "Kukatpally"],
  "Andhra Pradesh": ["Visakhapatnam", "Vijayawada", "Guntur", "Nellore", "Tirupati", "Kurnool", "Rajahmundry", "Kakinada"],
  Gujarat: ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Bhavnagar", "Jamnagar", "Gandhinagar", "Junagadh", "Anand"],
  Rajasthan: ["Jaipur", "Jodhpur", "Udaipur", "Kota", "Bikaner", "Ajmer", "Bhilwara", "Alwar", "Sikar"],
  "West Bengal": ["Kolkata", "Howrah", "Durgapur", "Asansol", "Siliguri", "Bardhaman", "Malda", "Baharampur"],
  "Uttar Pradesh": ["Lucknow", "Kanpur", "Agra", "Varanasi", "Meerut", "Prayagraj", "Ghaziabad", "Noida", "Aligarh"],
  Punjab: ["Chandigarh", "Ludhiana", "Amritsar", "Jalandhar", "Patiala", "Bathinda", "Mohali", "Hoshiarpur"],
  Haryana: ["Gurgaon", "Faridabad", "Panipat", "Ambala", "Rohtak", "Hisar", "Karnal", "Sonipat"],
  Madhya Pradesh: ["Bhopal", "Indore", "Jabalpur", "Gwalior", "Ujjain", "Ratlam", "Satna", "Rewa"],
  Odisha: ["Bhubaneswar", "Cuttack", "Rourkela", "Brahmapur", "Sambalpur", "Puri", "Balasore"],
};

export const INDIA_CITIES_FLAT = Object.values(INDIA_CITIES_BY_STATE).flat().sort();

// ─── Comprehensive Amenities ──────────────────────────────────────────────────
export const AMENITIES_LIST = [
  // Safety & Security
  "24/7 Security", "CCTV surveillance", "Intercom", "Gated community", "Security guard", "Video door phone",
  // Parking
  "Covered parking", "Open parking", "Two-wheeler parking", "Visitor parking", "EV charging point",
  // Utilities
  "Power backup", "Solar power", "Rainwater harvesting", "Borewell", "Overhead tank", "Gas pipeline",
  // Recreation
  "Swimming pool", "Children's play area", "Gymnasium", "Clubhouse", "Jogging track", "Yoga deck",
  "Indoor games", "Badminton court", "Tennis court", "Basketball court", "Multipurpose hall",
  // Convenience
  "Lift", "High-speed lifts", "Concierge", "Maintenance staff", "Housekeeping", "Garbage chute",
  "Laundry", "ATM on premises", "Supermarket nearby", "Medical clinic",
  // Digital & Smart
  "High-speed internet", "Wi-Fi in common areas", "Smart home features", "DTH connection",
  // Green & Environment
  "Garden / Landscaping", "Tree plantation", "Organic garden", "Green building certified",
  // Extra
  "Vastu compliant", "Senior citizen amenities", "Differently-abled friendly", "Pet friendly",
  "Home automation", "Rooftop terrace",
];

// ─── Stamp Duty & Registration Rates by State ─────────────────────────────────
export const STAMP_DUTY_RATES = {
  Kerala: { stampDuty: 8, registration: 2, notes: "Women buyers get 1% rebate" },
  Maharashtra: { stampDuty: 5, registration: 1, notes: "Reduced to 3% for women buyers in urban areas" },
  Karnataka: { stampDuty: 5, registration: 1, notes: "Additional 1% surcharge on properties above ₹45L" },
  "Tamil Nadu": { stampDuty: 7, registration: 4, notes: "Varies by area classification" },
  "Delhi NCR": { stampDuty: 6, registration: 1, notes: "Women buyers pay 4% stamp duty" },
  Telangana: { stampDuty: 4, registration: 0.5, notes: "Plus 1.5% transfer duty" },
  "Andhra Pradesh": { stampDuty: 5, registration: 1, notes: "Plus 1.5% transfer duty" },
  Gujarat: { stampDuty: 4.9, registration: 1, notes: "Women buyers: 4.9% as well" },
  Rajasthan: { stampDuty: 6, registration: 1, notes: "Women buyers pay 5%" },
  "West Bengal": { stampDuty: 6, registration: 1, notes: "Additional 1% for properties >₹25L" },
  "Uttar Pradesh": { stampDuty: 7, registration: 1, notes: "Women buyers pay 6%" },
  Punjab: { stampDuty: 7, registration: 1, notes: "Varies by municipality" },
  Haryana: { stampDuty: 7, registration: 1, notes: "Women buyers pay 5%" },
  "Madhya Pradesh": { stampDuty: 9.5, registration: 3, notes: "One of the highest rates in India" },
  Odisha: { stampDuty: 5, registration: 2, notes: "Concessional rates for affordable housing" },
};

// ─── RBI Reference Rates ─────────────────────────────────────────────────────
export const RBI_RATE_INFO = {
  repoRate: 6.5,
  lastUpdated: "June 2025",
  note: "RBI repo rate as of June 2025. Home loan rates are typically repo rate + 2–3%.",
  homeLoansRangeMin: 8.35,
  homeLoansRangeMax: 9.5,
  source: "https://www.rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx",
};

// ─── Market Trend Data (free static reference) ────────────────────────────────
export const MARKET_TRENDS = {
  Kochi: { yoyGrowthPct: 11.2, avgPricePerSqft: 4850, demandIndex: "High", hotLocalities: ["Kakkanad", "Edapally", "Thrippunithura"] },
  Trivandrum: { yoyGrowthPct: 8.7, avgPricePerSqft: 3950, demandIndex: "Medium", hotLocalities: ["Technopark", "Peroorkada", "Kowdiar"] },
  Kozhikode: { yoyGrowthPct: 9.1, avgPricePerSqft: 3400, demandIndex: "High", hotLocalities: ["Beypore", "Calicut Beach", "Medical College"] },
  Bangalore: { yoyGrowthPct: 14.3, avgPricePerSqft: 6800, demandIndex: "Very High", hotLocalities: ["Whitefield", "Sarjapur", "Hebbal", "Electronic City"] },
  Hyderabad: { yoyGrowthPct: 12.8, avgPricePerSqft: 5200, demandIndex: "Very High", hotLocalities: ["Gachibowli", "Kondapur", "Kukatpally", "Madhapur"] },
  Chennai: { yoyGrowthPct: 9.6, avgPricePerSqft: 5600, demandIndex: "High", hotLocalities: ["OMR", "Porur", "Perambur", "Velachery"] },
  Pune: { yoyGrowthPct: 13.1, avgPricePerSqft: 6200, demandIndex: "Very High", hotLocalities: ["Wakad", "Hinjewadi", "Kharadi", "Baner"] },
  Mumbai: { yoyGrowthPct: 7.4, avgPricePerSqft: 16500, demandIndex: "High", hotLocalities: ["Thane", "Navi Mumbai", "Panvel", "Andheri"] },
};

// ─── Extra Seed Properties ────────────────────────────────────────────────────
export const EXTRA_SEED_PROPERTIES = [
  {
    id: "re-3",
    title: "Prestige Greenfield Villa",
    price: "2.40 Cr",
    priceLabel: "2.40 Cr",
    priceValue: 240,
    area: "3200 sq ft",
    areaSqft: 3200,
    carpetAreaSqft: 2800,
    builtUpAreaSqft: 3200,
    location: "Bangalore",
    locality: "Whitefield",
    address: "Prestige Greenfield, Whitefield, Bangalore",
    landmark: "Near ITPL",
    mapLocationLat: 12.9698,
    mapLocationLng: 77.7500,
    type: "Villa",
    intent: "sale",
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200&h=800&fit=crop",
    mediaGallery: buildSeedMedia(
      "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200&h=800&fit=crop",
      "",
      "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
      "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
      ""
    ),
    bedrooms: 4,
    bathrooms: 4,
    floorNumber: null,
    totalFloors: 2,
    parkingSpots: 3,
    propertyAgeYears: 1,
    furnishing: "Semi Furnished",
    amenities: ["Swimming pool", "Garden / Landscaping", "Gated community", "Security guard", "Gymnasium", "Clubhouse"],
    sellerName: "Vikram Rao",
    sellerRole: "Builder",
    listedBy: "Builder",
    verified: true,
    verificationStatus: "Verified",
    reraNumber: "PRM/KA/RERA/1251/310/PR/171017/001925",
    titleDeedStatus: "verified",
    taxReceipt: true,
    buildingPermit: true,
    encumbranceCertificate: true,
    contactPhone: "+91 9900112233",
    whatsappNumber: "+91 9900112233",
    readyToMove: false,
    underConstruction: false,
    nearbySchoolKm: 1.8,
    nearbyHospitalKm: 3.2,
    nearbyMetroKm: 2.4,
    featured: true,
    postedOn: "2026-05-01",
    possession: "Dec 2026",
    description: "Luxury 4BHK independent villa in a gated community near ITPL Whitefield. Private garden, premium finishes, and excellent connectivity.",
    mapLabel: "Whitefield IT corridor",
    rating: 4.9,
    reviewCount: 12,
    premiumPlan: "Builder Pro",
    mediaCount: 8,
    hasVideoTour: false,
    leads: [],
    visits: [],
    chatPreview: [{ from: "Vikram Rao", text: "Site visit bookings available every weekend." }],
    reviews: [{ author: "Priya Nair", score: 5, comment: "Exceptional build quality and transparent pricing." }],
    languageSupport: ["English", "Kannada", "Hindi"],
    disputeCount: 0,
    status: "available",
  },
  {
    id: "re-4",
    title: "Sea View 2 BHK Apartment",
    price: "68 Lakhs",
    priceLabel: "68 Lakhs",
    priceValue: 68,
    area: "1180 sq ft",
    areaSqft: 1180,
    carpetAreaSqft: 940,
    builtUpAreaSqft: 1180,
    location: "Kozhikode",
    locality: "Calicut Beach",
    address: "Marine Drive Road, Calicut Beach, Kozhikode, Kerala",
    landmark: "Near Calicut Beach",
    mapLocationLat: 11.2499,
    mapLocationLng: 75.7766,
    type: "Apartment",
    intent: "sale",
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&h=800&fit=crop",
    mediaGallery: buildSeedMedia(
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&h=800&fit=crop",
      "",
      "",
      "",
      ""
    ),
    bedrooms: 2,
    bathrooms: 2,
    floorNumber: 7,
    totalFloors: 12,
    parkingSpots: 1,
    propertyAgeYears: 4,
    furnishing: "Furnished",
    amenities: ["Sea view", "24/7 Security", "Lift", "Covered parking", "Power backup"],
    sellerName: "Laila Hassan",
    sellerRole: "Owner",
    listedBy: "Owner",
    verified: true,
    verificationStatus: "Verified",
    reraNumber: "K-RERA/PRJ/KZD/2023/0054",
    titleDeedStatus: "verified",
    taxReceipt: true,
    buildingPermit: true,
    encumbranceCertificate: true,
    contactPhone: "+91 9876001122",
    whatsappNumber: "+91 9876001122",
    readyToMove: true,
    underConstruction: false,
    nearbySchoolKm: 0.9,
    nearbyHospitalKm: 1.4,
    nearbyMetroKm: null,
    featured: false,
    postedOn: "2026-04-22",
    possession: "Ready to move",
    description: "Rare sea-facing 2 BHK with unobstructed Arabian Sea views from the living room and master bedroom. Well-maintained society with active management.",
    mapLabel: "Calicut beach waterfront",
    rating: 4.7,
    reviewCount: 9,
    premiumPlan: "Featured",
    mediaCount: 6,
    hasVideoTour: false,
    leads: [],
    visits: [],
    chatPreview: [{ from: "Laila Hassan", text: "Negotiable for serious buyers. Can arrange immediate visit." }],
    reviews: [{ author: "Suresh Nambiar", score: 5, comment: "The sea view is worth every rupee." }],
    languageSupport: ["English", "Malayalam"],
    disputeCount: 0,
    status: "available",
  },
  {
    id: "re-5",
    title: "Prime Commercial Office Space",
    price: "1.85 Cr",
    priceLabel: "1.85 Cr",
    priceValue: 185,
    area: "2400 sq ft",
    areaSqft: 2400,
    location: "Hyderabad",
    locality: "Gachibowli",
    address: "Financial District, Gachibowli, Hyderabad",
    landmark: "Near DLF Cyber City",
    mapLocationLat: 17.4401,
    mapLocationLng: 78.3489,
    type: "Commercial",
    intent: "sale",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&h=800&fit=crop",
    mediaGallery: buildSeedMedia(
      "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&h=800&fit=crop",
      "",
      "",
      "",
      ""
    ),
    bedrooms: 0,
    bathrooms: 4,
    floorNumber: 14,
    totalFloors: 22,
    parkingSpots: 4,
    furnishing: "Furnished",
    amenities: ["High-speed internet", "24/7 Security", "Lift", "Power backup", "CCTV surveillance", "Concierge"],
    sellerName: "Rajesh Reddy",
    sellerRole: "Agent",
    listedBy: "Agent",
    verified: true,
    verificationStatus: "Verified",
    reraNumber: "P02400003451",
    titleDeedStatus: "verified",
    taxReceipt: true,
    buildingPermit: true,
    encumbranceCertificate: false,
    contactPhone: "+91 9988776655",
    whatsappNumber: "+91 9988776655",
    readyToMove: true,
    underConstruction: false,
    nearbySchoolKm: null,
    nearbyHospitalKm: 2.8,
    nearbyMetroKm: 1.6,
    featured: true,
    postedOn: "2026-04-25",
    possession: "Ready to move",
    description: "Grade-A commercial office in the Financial District with floor-to-ceiling glazing, raised flooring, and premium fit-outs. Ideal for tech or finance firms.",
    mapLabel: "Gachibowli Financial District",
    rating: 4.6,
    reviewCount: 7,
    premiumPlan: "Agent Pro",
    mediaCount: 5,
    hasVideoTour: false,
    leads: [],
    visits: [],
    chatPreview: [{ from: "Rajesh Reddy", text: "Happy to arrange a physical tour any weekday." }],
    reviews: [],
    languageSupport: ["English", "Telugu", "Hindi"],
    disputeCount: 0,
    status: "available",
  },
  {
    id: "re-6",
    title: "Affordable Plot — Residential Layout",
    price: "18 Lakhs",
    priceLabel: "18 Lakhs",
    priceValue: 18,
    area: "2400 sq ft",
    areaSqft: 2400,
    landSizeSqft: 2400,
    location: "Kochi",
    locality: "Thrippunithura",
    address: "Nettoor Road, Thrippunithura, Kochi",
    landmark: "Near Boat Jetty",
    mapLocationLat: 9.9560,
    mapLocationLng: 76.3190,
    type: "Plot",
    intent: "sale",
    image: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&h=800&fit=crop",
    mediaGallery: buildSeedMedia(
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&h=800&fit=crop",
      "", "", "", ""
    ),
    bedrooms: 0,
    bathrooms: 0,
    furnishing: "Unfurnished",
    amenities: ["Gated community", "CCTV surveillance", "Rainwater harvesting", "24/7 Security"],
    sellerName: "George Thomas",
    sellerRole: "Owner",
    listedBy: "Owner",
    verified: true,
    verificationStatus: "Verified",
    reraNumber: "",
    titleDeedStatus: "verified",
    taxReceipt: true,
    buildingPermit: false,
    encumbranceCertificate: true,
    contactPhone: "+91 9876543099",
    whatsappNumber: "+91 9876543099",
    readyToMove: true,
    underConstruction: false,
    nearbySchoolKm: 2.0,
    nearbyHospitalKm: 1.5,
    nearbyMetroKm: null,
    featured: false,
    postedOn: "2026-04-28",
    possession: "Immediate",
    description: "Clear-title residential plot in a fast-developing corridor. All utilities at the boundary. Ideal for building your dream home.",
    mapLabel: "Thrippunithura growth zone",
    rating: 4.3,
    reviewCount: 4,
    premiumPlan: "Starter",
    mediaCount: 3,
    hasVideoTour: false,
    leads: [],
    visits: [],
    chatPreview: [{ from: "George Thomas", text: "No disputes. Title deed and EC available immediately." }],
    reviews: [],
    languageSupport: ["English", "Malayalam"],
    disputeCount: 0,
    status: "available",
  },
];

// Merge all seed data into a single export used by the app
export const ALL_SEED_PROPERTIES = [
  ...REAL_ESTATE_SEED_PROPERTIES,
  ...EXTRA_SEED_PROPERTIES,
];
