export const ROLE_MODES = [
  {
    id: "buyer",
    title: "Buyer / Tenant",
    description: "Search verified properties, save favorites, and connect with sellers.",
  },
  {
    id: "owner",
    title: "Property Owner",
    description: "Post sale or rental listings with media, pricing, and amenities.",
  },
  {
    id: "agent",
    title: "Agent / Broker",
    description: "Manage multiple listings, premium boosts, and active leads.",
  },
  {
    id: "builder",
    title: "Builder / Developer",
    description: "Launch projects, manage inventory, and showcase unit availability.",
  },
  {
    id: "admin",
    title: "Admin",
    description: "Approve listings, verify users, monitor disputes, and track analytics.",
  },
];

export const CONSTRUCTION_SERVICES = [
  {
    id: "renovation",
    title: "Renovation & Interiors",
    description: "Design, budgeting, and trusted contractors for every home upgrade.",
  },
  {
    id: "project-launch",
    title: "Project Marketing",
    description: "Launch ready-to-sell inventory, virtual tours, and booking workflows.",
  },
  {
    id: "legal-support",
    title: "Legal & Documentation",
    description: "Title search, agreements, approvals and regulatory compliance support.",
  },
  {
    id: "tenant-services",
    title: "Tenant Services",
    description: "Rent collection, maintenance scheduling, and move-in welcome support.",
  },
];

export const HOME_LOAN_PARTNERS = [
  { name: "Nila Bank Home Loans", rate: 7.9 },
  { name: "Gulf Finance Partners", rate: 8.1 },
  { name: "Malabar Housing Credit", rate: 8.5 },
];

export const TENANT_UTILITIES = [
  "Rent payment reminders",
  "Maintenance request tracking",
  "Rental agreement templates",
  "Homeowner insurance guidance",
];

export const LEAD_STAGE_OPTIONS = [
  { value: "new", label: "New" },
  { value: "contacted", label: "Contacted" },
  { value: "site_visit", label: "Site Visit" },
  { value: "negotiation", label: "Negotiation" },
  { value: "token_paid", label: "Token Paid" },
  { value: "closed", label: "Closed" },
  { value: "lost", label: "Lost" },
];

export const LISTING_TYPE_OPTIONS = [
  "Apartment",
  "Flat",
  "Villa",
  "House",
  "Plot",
  "Land",
  "Commercial",
  "Office",
  "Shop",
  "Warehouse",
  "Farm land",
  "Studio",
];

export const TITLE_DEED_OPTIONS = [
  { value: "pending", label: "Pending" },
  { value: "verified", label: "Verified" },
  { value: "rejected", label: "Rejected" },
  { value: "not-applicable", label: "Not applicable" },
];

export const DEFAULT_LISTING_FORM = {
  title: "",
  intent: "sale",
  priceLabel: "",
  location: "",
  locality: "",
  type: "Flat",
  bedrooms: "2",
  bathrooms: "2",
  furnishing: "Semi Furnished",
  areaSqft: "",
  carpetAreaSqft: "",
  builtUpAreaSqft: "",
  landSizeSqft: "",
  floorNumber: "",
  totalFloors: "",
  parkingSpots: "",
  propertyAgeYears: "",
  possession: "Ready to move",
  address: "",
  landmark: "",
  contactPhone: "",
  whatsappNumber: "",
  mapLocationLat: "",
  mapLocationLng: "",
  videoTourUrl: "",
  floorPlanUrl: "",
  brochureUrl: "",
  mapPreviewUrl: "",
  mediaGalleryInput: "",
  amenitiesInput: "",
  nearbySchoolKm: "",
  nearbyHospitalKm: "",
  nearbyMetroKm: "",
  readyToMove: true,
  underConstruction: false,
  reraNumber: "",
  titleDeedStatus: "pending",
  taxReceipt: false,
  buildingPermit: false,
  encumbranceCertificate: false,
  description: "",
};

const buildSeedMedia = (image, video, floorPlan, brochure, mapPreview) => [
  { id: "m-1", type: "image", label: "Front view", url: image, order: 0 },
  ...(video ? [{ id: "m-2", type: "video", label: "Video tour", url: video, order: 1 }] : []),
  ...(floorPlan ? [{ id: "m-3", type: "floor-plan", label: "Floor plan", url: floorPlan, order: 2 }] : []),
  ...(brochure ? [{ id: "m-4", type: "brochure", label: "Brochure", url: brochure, order: 3 }] : []),
  ...(mapPreview ? [{ id: "m-5", type: "map", label: "Map preview", url: mapPreview, order: 4 }] : []),
];

export const REAL_ESTATE_SEED_PROPERTIES = [
  {
    id: "re-1",
    title: "Skyline Residency 3 BHK",
    price: "95 Lakhs",
    priceLabel: "95 Lakhs",
    priceValue: 95,
    area: "1650 sq ft",
    areaSqft: 1650,
    carpetAreaSqft: 1320,
    builtUpAreaSqft: 1650,
    landSizeSqft: null,
    location: "Kochi",
    locality: "Kakkanad",
    address: "Skyline Residency, Kakkanad, Kochi, Kerala",
    landmark: "Near SmartCity",
    mapLocationLat: 10.0159,
    mapLocationLng: 76.3419,
    mapPreviewUrl: "https://maps.googleapis.com/maps/api/staticmap?center=10.0159,76.3419&zoom=13&size=600x300",
    type: "Flat",
    intent: "sale",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&h=800&fit=crop",
    mediaGallery: buildSeedMedia(
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&h=800&fit=crop",
      "https://samplelib.com/lib/preview/mp4/sample-5s.mp4",
      "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
      "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
      "https://maps.googleapis.com/maps/api/staticmap?center=10.0159,76.3419&zoom=13&size=600x300"
    ),
    videoTourUrl: "https://samplelib.com/lib/preview/mp4/sample-5s.mp4",
    floorPlanUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    brochureUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    bedrooms: 3,
    bathrooms: 3,
    floorNumber: 12,
    totalFloors: 18,
    parkingSpots: 2,
    propertyAgeYears: 2,
    furnishing: "Semi Furnished",
    amenities: ["Covered parking", "Clubhouse", "Security", "Power backup"],
    sellerName: "Amina Niyas",
    sellerRole: "Owner",
    listedBy: "Owner",
    verified: true,
    verificationStatus: "Verified",
    reraNumber: "K-RERA/PRJ/KOCHI/1024",
    titleDeedStatus: "verified",
    taxReceipt: true,
    buildingPermit: true,
    encumbranceCertificate: true,
    contactPhone: "+91 9876543210",
    whatsappNumber: "+91 9876543210",
    readyToMove: true,
    underConstruction: false,
    nearbySchoolKm: 1.3,
    nearbyHospitalKm: 2.1,
    nearbyMetroKm: 1.1,
    featured: true,
    postedOn: "2026-04-18",
    possession: "Ready to move",
    description:
      "A family-ready apartment near the IT corridor with metro access, strong resale demand, and community amenities.",
    mapLabel: "Kakkanad smart city corridor",
    rating: 4.8,
    reviewCount: 36,
    premiumPlan: "Featured Listing",
    mediaCount: 12,
    hasVideoTour: true,
    leads: [{ id: "lead-1", name: "Riyas", channel: "Chat", priority: "Hot", status: "new" }],
    visits: [],
    chatPreview: [{ from: "Amina Niyas", text: "Floor plan and legal summary are ready to share." }],
    reviews: [{ author: "Shahid", score: 5, comment: "Verified documents and fast site visit support." }],
    languageSupport: ["English", "Malayalam"],
    disputeCount: 0,
    status: "available",
  },
  {
    id: "re-2",
    title: "Smart Rental Studio",
    price: "28,000 / month",
    priceLabel: "28,000 / month",
    priceValue: 28,
    area: "640 sq ft",
    areaSqft: 640,
    carpetAreaSqft: 510,
    builtUpAreaSqft: 640,
    location: "Trivandrum",
    locality: "Technopark Phase 1",
    address: "Technopark Phase 1, Trivandrum, Kerala",
    type: "Studio",
    intent: "rent",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200&h=800&fit=crop",
    mediaGallery: buildSeedMedia(
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200&h=800&fit=crop",
      "",
      "",
      "",
      ""
    ),
    bedrooms: 1,
    bathrooms: 1,
    furnishing: "Furnished",
    amenities: ["Wi-Fi", "Lift", "Security", "Housekeeping access"],
    sellerName: "Rohit Menon",
    sellerRole: "Owner",
    listedBy: "Owner",
    verified: true,
    verificationStatus: "Verified",
    reraNumber: "",
    titleDeedStatus: "verified",
    taxReceipt: true,
    buildingPermit: true,
    encumbranceCertificate: false,
    readyToMove: true,
    underConstruction: false,
    nearbySchoolKm: 3.4,
    nearbyHospitalKm: 1.9,
    nearbyMetroKm: null,
    featured: false,
    postedOn: "2026-04-19",
    possession: "Immediate",
    description: "Compact and fully furnished studio for quick move-in professionals.",
    mapLabel: "Technopark rental cluster",
    rating: 4.4,
    reviewCount: 19,
    premiumPlan: "Starter",
    mediaCount: 9,
    hasVideoTour: false,
    leads: [{ id: "lead-2", name: "Devika", channel: "Call", priority: "Warm", status: "contacted" }],
    reviews: [{ author: "Arun", score: 4, comment: "Well-maintained and easy move-in process." }],
    languageSupport: ["English", "Malayalam", "Tamil"],
    disputeCount: 0,
    status: "available",
  },
];

export const SUBSCRIPTION_PLANS = [
  { id: "starter", name: "Starter", amountInr: 499, featuredCredits: 1, listingLimit: 1, durationDays: 30 },
  { id: "featured", name: "Featured", amountInr: 1499, featuredCredits: 5, listingLimit: 5, durationDays: 30 },
  { id: "agent-pro", name: "Agent Pro", amountInr: 2999, featuredCredits: 15, listingLimit: 999, durationDays: 30 },
  { id: "builder-pro", name: "Builder Pro", amountInr: 4999, featuredCredits: 35, listingLimit: 999, durationDays: 30 },
];

