/**
 * Demo Messaging Data - Seeded realistic conversations
 * Provides authentic-feeling demo data for LinkUp messaging
 * Used to fill empty state and create "alive" feeling
 */

// Helper: Generate time relative to now
const timeAgo = (minutes) => new Date(Date.now() - minutes * 60000);

// Demo Users
export const DEMO_USERS = {
  supportTeam: {
    _id: 'support-team-1',
    name: 'Support Team',
    avatar: '🎯',
    role: 'support',
    online: true,
    lastSeen: 'now',
  },
  deliveryDriver: {
    _id: 'delivery-driver-1',
    name: 'Ajay - Delivery Driver',
    avatar: '🚴',
    role: 'delivery',
    online: true,
    lastSeen: '2m',
  },
  marketplaceSeller: {
    _id: 'seller-1',
    name: 'TechStore Marketplace',
    avatar: '🛍️',
    role: 'seller',
    online: true,
    lastSeen: '1m',
  },
  rideDriver: {
    _id: 'driver-1',
    name: 'Rahul - Your Ride Driver',
    avatar: '🚗',
    role: 'driver',
    online: true,
    lastSeen: 'now',
  },
  friend: {
    _id: 'friend-1',
    name: 'Priya',
    avatar: '👩‍🦰',
    role: 'friend',
    online: false,
    lastSeen: '15m',
  },
  communityGroup: {
    _id: 'group-1',
    name: 'Bangalore Tech Community',
    avatar: '👥',
    role: 'group',
    members: 247,
    lastSeen: null,
  },
};

// Demo Conversations
export const DEMO_CONVERSATIONS = [
  {
    _id: 'conv-support-1',
    type: 'direct',
    participants: [DEMO_USERS.supportTeam],
    groupName: 'Support Team',
    lastMessage: {
      _id: 'msg-support-5',
      content: 'Your issue has been resolved! Order #ORD12345 is confirmed.',
      sender: DEMO_USERS.supportTeam,
      createdAt: timeAgo(5),
      messageType: 'text',
      read: false,
    },
    lastMessageAt: timeAgo(5),
    unreadCount: 1,
    category: 'support',
    icon: '🎯',
  },
  {
    _id: 'conv-delivery-1',
    type: 'direct',
    participants: [DEMO_USERS.deliveryDriver],
    groupName: 'Delivery Updates',
    lastMessage: {
      _id: 'msg-delivery-3',
      content: '📍 I\'m 5 mins away. Your order #ORD12346 is on the way!',
      sender: DEMO_USERS.deliveryDriver,
      createdAt: timeAgo(3),
      messageType: 'text',
      read: true,
    },
    lastMessageAt: timeAgo(3),
    unreadCount: 0,
    category: 'delivery',
    icon: '🚴',
    typing: false,
  },
  {
    _id: 'conv-seller-1',
    type: 'direct',
    participants: [DEMO_USERS.marketplaceSeller],
    groupName: 'TechStore Marketplace',
    lastMessage: {
      _id: 'msg-seller-4',
      content: 'Sure! I can negotiate. What\'s your best offer?',
      sender: DEMO_USERS.marketplaceSeller,
      createdAt: timeAgo(8),
      messageType: 'text',
      read: true,
    },
    lastMessageAt: timeAgo(8),
    unreadCount: 0,
    category: 'marketplace',
    icon: '🛍️',
    typing: false,
  },
  {
    _id: 'conv-driver-1',
    type: 'direct',
    participants: [DEMO_USERS.rideDriver],
    groupName: 'Your Ride Driver - Rahul',
    lastMessage: {
      _id: 'msg-driver-2',
      content: '✓ Arrived at pickup location. I\'m waiting outside.',
      sender: DEMO_USERS.rideDriver,
      createdAt: timeAgo(2),
      messageType: 'text',
      read: false,
    },
    lastMessageAt: timeAgo(2),
    unreadCount: 1,
    category: 'rideshare',
    icon: '🚗',
    typing: false,
  },
  {
    _id: 'conv-friend-1',
    type: 'direct',
    participants: [DEMO_USERS.friend],
    groupName: 'Priya',
    lastMessage: {
      _id: 'msg-friend-6',
      content: 'Haha that\'s hilarious! 😂 See you tomorrow at the cafe!',
      sender: DEMO_USERS.friend,
      createdAt: timeAgo(45),
      messageType: 'text',
      read: true,
    },
    lastMessageAt: timeAgo(45),
    unreadCount: 0,
    category: 'personal',
    icon: '👩‍🦰',
    typing: false,
  },
  {
    _id: 'conv-community-1',
    type: 'group',
    participants: [DEMO_USERS.communityGroup],
    groupName: 'Bangalore Tech Community',
    lastMessage: {
      _id: 'msg-community-12',
      content: 'Amazing! That\'s the new feature everyone was asking for 🎉',
      sender: { _id: 'member-1', name: 'Arun' },
      createdAt: timeAgo(12),
      messageType: 'text',
      read: true,
    },
    lastMessageAt: timeAgo(12),
    unreadCount: 0,
    category: 'community',
    icon: '👥',
    members: 247,
    typing: false,
  },
];

// Full message history for each conversation
export const DEMO_MESSAGES = {
  'conv-support-1': [
    {
      _id: 'msg-support-1',
      chatId: 'conv-support-1',
      sender: DEMO_USERS.supportTeam,
      content: 'Hi! Thank you for contacting NilaHub Support. How can I help you today?',
      createdAt: timeAgo(120),
      messageType: 'text',
      read: true,
    },
    {
      _id: 'msg-support-2',
      chatId: 'conv-support-1',
      sender: { _id: 'user-current', name: 'You' },
      content: 'Hi, I have a question about my order from yesterday',
      createdAt: timeAgo(110),
      messageType: 'text',
      read: true,
    },
    {
      _id: 'msg-support-3',
      chatId: 'conv-support-1',
      sender: DEMO_USERS.supportTeam,
      content: 'Of course! Could you please provide your order number?',
      createdAt: timeAgo(105),
      messageType: 'text',
      read: true,
    },
    {
      _id: 'msg-support-4',
      chatId: 'conv-support-1',
      sender: { _id: 'user-current', name: 'You' },
      content: 'Yes, it\'s ORD12345. I wanted to know the estimated delivery time.',
      createdAt: timeAgo(100),
      messageType: 'text',
      read: true,
    },
    {
      _id: 'msg-support-5',
      chatId: 'conv-support-1',
      sender: DEMO_USERS.supportTeam,
      content: 'Your issue has been resolved! Order #ORD12345 is confirmed.',
      createdAt: timeAgo(5),
      messageType: 'text',
      read: false,
    },
  ],
  'conv-delivery-1': [
    {
      _id: 'msg-delivery-1',
      chatId: 'conv-delivery-1',
      sender: DEMO_USERS.deliveryDriver,
      content: 'Hi! I\'ll be delivering your order today 🚴',
      createdAt: timeAgo(60),
      messageType: 'text',
      read: true,
    },
    {
      _id: 'msg-delivery-2',
      chatId: 'conv-delivery-1',
      sender: { _id: 'user-current', name: 'You' },
      content: 'Great! When should I expect the delivery?',
      createdAt: timeAgo(55),
      messageType: 'text',
      read: true,
    },
    {
      _id: 'msg-delivery-3',
      chatId: 'conv-delivery-1',
      sender: DEMO_USERS.deliveryDriver,
      content: '📍 I\'m 5 mins away. Your order #ORD12346 is on the way!',
      createdAt: timeAgo(3),
      messageType: 'text',
      read: true,
    },
  ],
  'conv-seller-1': [
    {
      _id: 'msg-seller-1',
      chatId: 'conv-seller-1',
      sender: { _id: 'user-current', name: 'You' },
      content: 'Hi! Is the laptop still available? Can you negotiate on price?',
      createdAt: timeAgo(30),
      messageType: 'text',
      read: true,
    },
    {
      _id: 'msg-seller-2',
      chatId: 'conv-seller-1',
      sender: DEMO_USERS.marketplaceSeller,
      content: 'Yes, it\'s available! It\'s in perfect condition.',
      createdAt: timeAgo(25),
      messageType: 'text',
      read: true,
    },
    {
      _id: 'msg-seller-3',
      chatId: 'conv-seller-1',
      sender: { _id: 'user-current', name: 'You' },
      content: 'I can offer 10% less. Would that work?',
      createdAt: timeAgo(15),
      messageType: 'text',
      read: true,
    },
    {
      _id: 'msg-seller-4',
      chatId: 'conv-seller-1',
      sender: DEMO_USERS.marketplaceSeller,
      content: 'Sure! I can negotiate. What\'s your best offer?',
      createdAt: timeAgo(8),
      messageType: 'text',
      read: true,
    },
  ],
  'conv-driver-1': [
    {
      _id: 'msg-driver-1',
      chatId: 'conv-driver-1',
      sender: DEMO_USERS.rideDriver,
      content: '✓ I\'ve started your ride. ETA 8 minutes.',
      createdAt: timeAgo(10),
      messageType: 'text',
      read: true,
    },
    {
      _id: 'msg-driver-2',
      chatId: 'conv-driver-1',
      sender: DEMO_USERS.rideDriver,
      content: '✓ Arrived at pickup location. I\'m waiting outside.',
      createdAt: timeAgo(2),
      messageType: 'text',
      read: false,
    },
  ],
  'conv-friend-1': [
    {
      _id: 'msg-friend-1',
      chatId: 'conv-friend-1',
      sender: { _id: 'user-current', name: 'You' },
      content: 'Hey Priya! What are you up to? 😊',
      createdAt: timeAgo(60),
      messageType: 'text',
      read: true,
    },
    {
      _id: 'msg-friend-2',
      chatId: 'conv-friend-1',
      sender: DEMO_USERS.friend,
      content: 'Hey! Just finished work, super tired 😴',
      createdAt: timeAgo(55),
      messageType: 'text',
      read: true,
    },
    {
      _id: 'msg-friend-3',
      chatId: 'conv-friend-1',
      sender: { _id: 'user-current', name: 'You' },
      content: 'Aw, let\'s get coffee tomorrow? I\'ll treat you! ☕',
      createdAt: timeAgo(50),
      messageType: 'text',
      read: true,
    },
    {
      _id: 'msg-friend-4',
      chatId: 'conv-friend-1',
      sender: DEMO_USERS.friend,
      content: 'YES please! I need a break from work stress 😅',
      createdAt: timeAgo(48),
      messageType: 'text',
      read: true,
    },
    {
      _id: 'msg-friend-5',
      chatId: 'conv-friend-1',
      sender: { _id: 'user-current', name: 'You' },
      content: 'Cool! Cafe Coffee Day at 3pm? I\'ll book our table!',
      createdAt: timeAgo(46),
      messageType: 'text',
      read: true,
    },
    {
      _id: 'msg-friend-6',
      chatId: 'conv-friend-1',
      sender: DEMO_USERS.friend,
      content: 'Haha that\'s hilarious! 😂 See you tomorrow at the cafe!',
      createdAt: timeAgo(45),
      messageType: 'text',
      read: true,
    },
  ],
  'conv-community-1': [
    {
      _id: 'msg-community-1',
      chatId: 'conv-community-1',
      sender: { _id: 'member-5', name: 'Sneha' },
      content: 'Just launched our new feature! Super excited about it 🚀',
      createdAt: timeAgo(30),
      messageType: 'text',
      read: true,
    },
    {
      _id: 'msg-community-2',
      chatId: 'conv-community-1',
      sender: { _id: 'member-2', name: 'Vikram' },
      content: 'Wow! What does it do? Tell us more!',
      createdAt: timeAgo(25),
      messageType: 'text',
      read: true,
    },
    {
      _id: 'msg-community-3',
      chatId: 'conv-community-1',
      sender: { _id: 'member-5', name: 'Sneha' },
      content: 'It allows real-time collaboration! Great for teams 💪',
      createdAt: timeAgo(20),
      messageType: 'text',
      read: true,
    },
    {
      _id: 'msg-community-4',
      chatId: 'conv-community-1',
      sender: { _id: 'member-3', name: 'Aditya' },
      content: 'That\'s exactly what the community was asking for!',
      createdAt: timeAgo(15),
      messageType: 'text',
      read: true,
    },
    {
      _id: 'msg-community-12',
      chatId: 'conv-community-1',
      sender: { _id: 'member-1', name: 'Arun' },
      content: 'Amazing! That\'s the new feature everyone was asking for 🎉',
      createdAt: timeAgo(12),
      messageType: 'text',
      read: true,
    },
  ],
};

// Suggested contacts for quick action
export const SUGGESTED_CONTACTS = [
  {
    _id: 'contact-1',
    name: 'Marketplace Support',
    avatar: '💬',
    reason: 'Recently viewed your items',
    online: true,
  },
  {
    _id: 'contact-2',
    name: 'Local Deals Community',
    avatar: '🏷️',
    reason: '45 members, very active',
    online: null,
  },
  {
    _id: 'contact-3',
    name: 'Tech Freelancers Network',
    avatar: '💼',
    reason: 'Your profile matches 92%',
    online: null,
  },
];

// Quick actions for empty state
export const QUICK_ACTIONS = [
  {
    id: 'action-negotiate',
    icon: '🤝',
    title: 'Start marketplace negotiation',
    description: 'Message sellers about deals',
    action: 'marketplace',
  },
  {
    id: 'action-delivery',
    icon: '🚴',
    title: 'Contact delivery person',
    description: 'Track your order in real-time',
    action: 'delivery',
  },
  {
    id: 'action-driver',
    icon: '🚗',
    title: 'Message your ride driver',
    description: 'Communicate during your trip',
    action: 'rideshare',
  },
  {
    id: 'action-support',
    icon: '🎯',
    title: 'Get instant support',
    description: 'Talk to our support team',
    action: 'support',
  },
  {
    id: 'action-group',
    icon: '👥',
    title: 'Join community group',
    description: 'Connect with like-minded people',
    action: 'community',
  },
  {
    id: 'action-friend',
    icon: '👋',
    title: 'Invite a friend',
    description: 'Start a personal chat',
    action: 'friends',
  },
];

// Export all demo data
export const getDemoConversations = () => DEMO_CONVERSATIONS;
export const getDemoMessages = (chatId) => DEMO_MESSAGES[chatId] || [];
export const getDemoUsers = () => DEMO_USERS;
export const getSuggestedContacts = () => SUGGESTED_CONTACTS;
export const getQuickActions = () => QUICK_ACTIONS;

export default {
  DEMO_USERS,
  DEMO_CONVERSATIONS,
  DEMO_MESSAGES,
  SUGGESTED_CONTACTS,
  QUICK_ACTIONS,
  getDemoConversations,
  getDemoMessages,
  getDemoUsers,
  getSuggestedContacts,
  getQuickActions,
};
