const DEFAULT_BUSINESS_CATEGORIES = [
  { id: 'ecommerce', name: 'GlobeMart', fee: 799, requiresFoodLicense: false },
  { id: 'messaging', name: 'LinkUp', fee: 999, requiresFoodLicense: false },
  { id: 'classifieds', name: 'TradePost', fee: 1299, requiresFoodLicense: false },
  { id: 'realestate', name: 'HomeSphere', fee: 1499, requiresFoodLicense: false },
  { id: 'fooddelivery', name: 'Feastly', fee: 1999, requiresFoodLicense: true },
  { id: 'ridesharing', name: 'SwiftRide', fee: 1099, requiresFoodLicense: false },
  { id: 'matrimonial', name: 'SoulMatch', fee: 1599, requiresFoodLicense: false },
  { id: 'socialmedia', name: 'VibeHub', fee: 899, requiresFoodLicense: false },
  { id: 'reminderalert', name: 'ReminderAlert FRS', fee: 1199, requiresFoodLicense: false },
  { id: 'sosalert', name: 'SOS FRS', fee: 1399, requiresFoodLicense: false },
];

const DEFAULT_APP_DATA = {
  businessCategories: DEFAULT_BUSINESS_CATEGORIES,
  globeMartCategories: [
    {
      id: 'electronics',
      name: 'Electronics',
      theme: 'Tech Essentials',
      accentColor: '#0f4c81',
      subcategories: [
        'Mobiles & Accessories',
        'Laptops & Accessories',
        'TV & Home Entertainment',
        'Audio',
        'Cameras',
        'Computer Peripherals',
      ],
    },
    {
      id: 'fashion',
      name: 'Fashion',
      theme: 'Everyday Style',
      accentColor: '#a63a50',
      subcategories: ['Men', 'Women', 'Kids', 'Footwear', 'Bags', 'Jewellery'],
    },
    {
      id: 'home',
      name: 'Home',
      theme: 'Warm Living',
      accentColor: '#7b5e3b',
      subcategories: ['Kitchen', 'Furniture', 'Decor', 'Lighting', 'Storage'],
    },
    {
      id: 'accessories',
      name: 'Accessories',
      theme: 'Daily Add-ons',
      accentColor: '#26734d',
      subcategories: ['Chargers', 'Cases', 'Cables', 'Wearables', 'Travel Gear'],
    },
  ],
  enabledModules: DEFAULT_BUSINESS_CATEGORIES.map((category) => category.id),
  registrationApplications: [],
  registeredAccounts: [],
  moduleData: {
    ecommerceProducts: [
      {
        id: 1,
        name: 'Wireless Headphones',
        price: 3999,
        category: 'Electronics',
        image: 'Headphones',
        rating: 4.5,
        reviews: 234,
        stock: 18,
        businessName: 'SoundSphere Electronics',
        sellerName: 'Rajesh Kumar',
        location: 'Bangalore',
        description: 'Noise-cancelling headphones for work and travel.',
      },
      {
        id: 2,
        name: 'Smart Watch',
        price: 7999,
        category: 'Electronics',
        image: 'Smart watch',
        rating: 4.2,
        reviews: 156,
        stock: 11,
        businessName: 'TechNova Hub',
        sellerName: 'Priya Singh',
        location: 'Delhi',
        description: 'Fitness tracking, call alerts, and premium battery life.',
      },
      {
        id: 3,
        name: 'Running Shoes',
        price: 5999,
        category: 'Fashion',
        image: 'Running shoes',
        rating: 4.7,
        reviews: 345,
        stock: 26,
        businessName: 'Stride Style Co.',
        sellerName: 'Arjun Patel',
        location: 'Mumbai',
        description: 'Lightweight running shoes with all-day comfort.',
      },
      {
        id: 4,
        name: 'Coffee Maker',
        price: 4499,
        category: 'Home',
        image: 'Coffee maker',
        rating: 4.3,
        reviews: 89,
        stock: 9,
        businessName: 'HomeBrew Essentials',
        sellerName: 'Neha Sharma',
        location: 'Pune',
        description: 'Compact coffee maker for quick home brewing.',
      },
      {
        id: 5,
        name: 'USB-C Cable',
        price: 599,
        category: 'Accessories',
        image: 'USB-C cable',
        rating: 4.6,
        reviews: 567,
        stock: 50,
        businessName: 'CableCraft Store',
        sellerName: 'Vikram Singh',
        location: 'Kochi',
        description: 'Durable fast-charging cable for phones and laptops.',
      },
    ],
    classifiedsListings: [
      {
        id: 'cl-1',
        title: 'iPhone 14 Pro 256 GB',
        description:
          'Box, charger, and bill included. Battery health is strong and the phone is ready for same-day pickup.',
        price: 65000,
        category: 'Electronics',
        seller: 'Rajesh Kumar',
        sellerRole: 'Verified Seller',
        sellerEmail: 'rajesh.kumar@example.com',
        location: 'Kochi',
        locality: 'Edappally',
        image: 'Phone',
        posted: '2026-04-19',
        condition: 'Used',
        featured: true,
        urgent: false,
        verified: true,
        views: 482,
        favorites: 39,
        chats: 1,
        languageSupport: ['English', 'Malayalam'],
        tags: ['Mobile', 'Apple', 'Bill available'],
        mapLabel: 'Edappally metro retail zone',
        contactOptions: ['Chat', 'Call'],
        mediaGallery: ['Front view', 'Back view', 'Battery health', 'Invoice'],
        monetizationPlan: 'Featured',
      },
      {
        id: 'cl-2',
        title: 'Royal Enfield Classic 350',
        description:
          'Single-owner bike with service history, insurance, and clean documents. Great fit for city rides and weekend trips.',
        price: 138000,
        category: 'Vehicles',
        seller: 'Priya Singh',
        sellerRole: 'Dealer',
        sellerEmail: 'priya.singh@example.com',
        location: 'Calicut',
        locality: 'Mavoor Road',
        image: 'Bicycle',
        posted: '2026-04-18',
        condition: 'Used',
        featured: true,
        urgent: true,
        verified: true,
        views: 645,
        favorites: 51,
        chats: 0,
        languageSupport: ['English', 'Malayalam', 'Hindi'],
        tags: ['Bike', 'Documents clear', 'Insurance active'],
        mapLabel: 'Mavoor Road vehicle hub',
        contactOptions: ['Chat', 'Call'],
        mediaGallery: ['Profile shot', 'Odometer', 'Registration', 'Service record'],
        monetizationPlan: 'Featured',
      },
      {
        id: 'cl-3',
        title: '2 BHK Rental near Infopark',
        description:
          'Family-friendly apartment with parking, security, and quick access to schools and the IT corridor.',
        price: 22000,
        category: 'Real Estate',
        seller: 'Arjun Patel',
        sellerRole: 'Owner',
        sellerEmail: 'arjun.patel@example.com',
        location: 'Kochi',
        locality: 'Kakkanad',
        image: 'Apartment',
        posted: '2026-04-20',
        condition: 'New',
        featured: false,
        urgent: false,
        verified: true,
        views: 321,
        favorites: 17,
        chats: 0,
        languageSupport: ['English', 'Malayalam', 'Tamil'],
        tags: ['Rental', 'Parking', 'Near Infopark'],
        mapLabel: 'Kakkanad smart city belt',
        contactOptions: ['Chat', 'Call'],
        mediaGallery: ['Living room', 'Bedroom', 'Kitchen', 'Parking'],
        monetizationPlan: 'Free',
      },
      {
        id: 'cl-4',
        title: 'Home AC Service Visit',
        description:
          'Same-day service slots available with cleaning, gas check, and repair estimate support.',
        price: 799,
        category: 'Services',
        seller: 'Neha Sharma',
        sellerRole: 'Service Provider',
        sellerEmail: 'neha.sharma@example.com',
        location: 'Kannur',
        locality: 'Talap',
        image: 'Service',
        posted: '2026-04-16',
        condition: 'New',
        featured: false,
        urgent: false,
        verified: true,
        views: 188,
        favorites: 14,
        chats: 0,
        languageSupport: ['English', 'Malayalam', 'Hindi'],
        tags: ['AC repair', 'Doorstep', 'Weekend slots'],
        mapLabel: 'Talap home services zone',
        contactOptions: ['Chat', 'Call'],
        mediaGallery: ['Technician ID', 'Service package', 'Customer rating'],
        monetizationPlan: 'Free',
      },
    ],
    classifiedsMessages: [
      {
        id: 'cl-msg-1',
        listingId: 'cl-1',
        from: 'Platform Bot',
        senderEmail: 'system@malabarbazaar.local',
        text: 'Verified listing. You can chat or call the seller directly.',
        createdAt: '2026-04-19T10:00:00.000Z',
      },
    ],
    classifiedsReports: [],
    realestateProperties: [
      {
        id: 're-1',
        title: 'Skyline Residency 3 BHK',
        price: '95 Lakhs',
        priceLabel: '95 Lakhs',
        priceValue: 95,
        area: '1650 sq ft',
        areaSqft: 1650,
        location: 'Kochi',
        locality: 'Kakkanad',
        type: 'Flat',
        intent: 'sale',
        image: 'Skyline tower',
        bedrooms: 3,
        bathrooms: 3,
        furnishing: 'Semi Furnished',
        amenities: ['Covered parking', 'Clubhouse', 'Security', 'Power backup'],
        sellerName: 'Amina Niyas',
        sellerRole: 'Owner',
        listedBy: 'Owner',
        verified: true,
        verificationStatus: 'Verified',
        featured: true,
        postedOn: '2026-04-18',
        possession: 'Ready to move',
        description: 'A family-ready apartment near the IT corridor with metro access, strong resale demand, and community amenities.',
        mapLabel: 'Kakkanad smart city corridor',
        rating: 4.8,
        reviewCount: 36,
        premiumPlan: 'Featured Listing',
        mediaCount: 12,
        hasVideoTour: true,
        leads: [
          { name: 'Riyas', channel: 'Chat', priority: 'Hot' },
          { name: 'Aparna', channel: 'Call', priority: 'Warm' },
        ],
        chatPreview: [
          { from: 'Amina Niyas', text: 'The price is negotiable for immediate buyers.' },
          { from: 'Platform Bot', text: 'Floor plan and legal summary are available on request.' },
        ],
        reviews: [
          { author: 'Shahid', score: 5, comment: 'Verified documents and fast site visit support.' },
          { author: 'Maya', score: 4, comment: 'Responsive owner and good neighborhood access.' },
        ],
        languageSupport: ['English', 'Malayalam'],
        disputeCount: 0,
      },
      {
        id: 're-2',
        title: 'Seabreeze Garden Villa',
        price: '2.4 Crores',
        priceLabel: '2.4 Crores',
        priceValue: 240,
        area: '4200 sq ft',
        areaSqft: 4200,
        location: 'Calicut',
        locality: 'Beypore',
        type: 'Villa',
        intent: 'sale',
        image: 'Luxury villa',
        bedrooms: 4,
        bathrooms: 4,
        furnishing: 'Furnished',
        amenities: ['Private garden', 'CCTV', 'Modular kitchen', 'Waterfront access'],
        sellerName: 'Nadira Estates',
        sellerRole: 'Agent',
        listedBy: 'Agent',
        verified: true,
        verificationStatus: 'Verified',
        featured: true,
        postedOn: '2026-04-16',
        possession: 'Ready to move',
        description: 'Premium waterfront villa curated for end users and NRI investors looking for a landmark address in North Kerala.',
        mapLabel: 'Beypore marina belt',
        rating: 4.9,
        reviewCount: 22,
        premiumPlan: 'Agent Pro',
        mediaCount: 18,
        hasVideoTour: true,
        leads: [
          { name: 'Fathima', channel: 'Enquiry', priority: 'Hot' },
          { name: 'Joseph', channel: 'Chat', priority: 'Warm' },
        ],
        chatPreview: [
          { from: 'Nadira Estates', text: 'We can arrange a virtual tour for outstation buyers.' },
        ],
        reviews: [
          { author: 'Nived', score: 5, comment: 'Great coordination and transparent pricing.' },
        ],
        languageSupport: ['English', 'Malayalam', 'Hindi'],
        disputeCount: 0,
      },
      {
        id: 're-3',
        title: 'Smart Rental Studio',
        price: '28,000 / month',
        priceLabel: '28,000 / month',
        priceValue: 28,
        area: '640 sq ft',
        areaSqft: 640,
        location: 'Trivandrum',
        locality: 'Technopark Phase 1',
        type: 'Studio',
        intent: 'rent',
        image: 'Rental studio',
        bedrooms: 1,
        bathrooms: 1,
        furnishing: 'Furnished',
        amenities: ['Wi-Fi', 'Lift', 'Security', 'Housekeeping access'],
        sellerName: 'Rohit Menon',
        sellerRole: 'Owner',
        listedBy: 'Owner',
        verified: true,
        verificationStatus: 'Verified',
        featured: false,
        postedOn: '2026-04-19',
        possession: 'Immediate',
        description: 'Compact and fully furnished studio close to the IT park, built for young professionals and short commute living.',
        mapLabel: 'Technopark rental cluster',
        rating: 4.4,
        reviewCount: 19,
        premiumPlan: 'Starter',
        mediaCount: 9,
        hasVideoTour: false,
        leads: [
          { name: 'Devika', channel: 'Call', priority: 'Warm' },
          { name: 'Nikhil', channel: 'Chat', priority: 'Warm' },
        ],
        chatPreview: [
          { from: 'Rohit Menon', text: 'Rent includes maintenance. Security deposit is three months.' },
        ],
        reviews: [
          { author: 'Arun', score: 4, comment: 'Well-maintained and easy move-in process.' },
        ],
        languageSupport: ['English', 'Malayalam', 'Tamil'],
        disputeCount: 0,
      },
      {
        id: 're-4',
        title: 'Town Square Commercial Floor',
        price: '1.35 Crores',
        priceLabel: '1.35 Crores',
        priceValue: 135,
        area: '2200 sq ft',
        areaSqft: 2200,
        location: 'Thrissur',
        locality: 'MG Road',
        type: 'Commercial',
        intent: 'sale',
        image: 'Commercial space',
        bedrooms: 0,
        bathrooms: 2,
        furnishing: 'Unfurnished',
        amenities: ['Road frontage', 'Elevator', 'Power backup', 'Visitor parking'],
        sellerName: 'Metro Asset Brokers',
        sellerRole: 'Agent',
        listedBy: 'Agent',
        verified: false,
        verificationStatus: 'Pending',
        featured: false,
        postedOn: '2026-04-15',
        possession: 'Ready to fit out',
        description: 'High-visibility commercial inventory suited for clinics, offices, and branded retail expansion in central Thrissur.',
        mapLabel: 'MG Road business district',
        rating: 4.2,
        reviewCount: 11,
        premiumPlan: 'Featured Listing',
        mediaCount: 10,
        hasVideoTour: true,
        leads: [{ name: 'Suresh', channel: 'Enquiry', priority: 'Hot' }],
        chatPreview: [
          { from: 'Metro Asset Brokers', text: 'We can share footfall data and rental yield estimates.' },
        ],
        reviews: [
          { author: 'Retail partner', score: 4, comment: 'Good access and clear commercial approvals.' },
        ],
        languageSupport: ['English', 'Malayalam', 'Hindi'],
        disputeCount: 1,
      },
      {
        id: 're-5',
        title: 'Green Haven Plots',
        price: '18 Lakhs onwards',
        priceLabel: '18 Lakhs onwards',
        priceValue: 18,
        area: '2400 sq ft',
        areaSqft: 2400,
        location: 'Kannur',
        locality: 'Taliparamba',
        type: 'Land',
        intent: 'sale',
        image: 'Residential plots',
        bedrooms: 0,
        bathrooms: 0,
        furnishing: 'Unfurnished',
        amenities: ['Compound wall', 'Drainage', 'Wide road', 'Clear title'],
        sellerName: 'Malabar Land Makers',
        sellerRole: 'Builder',
        listedBy: 'Builder',
        verified: true,
        verificationStatus: 'Verified',
        featured: false,
        postedOn: '2026-04-17',
        possession: 'Immediate registration',
        description: 'Approved villa plots in a fast-growing residential pocket with strong end-user demand and financing support.',
        mapLabel: 'Taliparamba residential expansion zone',
        rating: 4.6,
        reviewCount: 14,
        premiumPlan: 'Agent Pro',
        mediaCount: 7,
        hasVideoTour: false,
        leads: [{ name: 'Akhil', channel: 'Call', priority: 'Warm' }],
        chatPreview: [
          { from: 'Malabar Land Makers', text: 'Plot sizes can be combined for larger villa development.' },
        ],
        reviews: [
          { author: 'Investor', score: 5, comment: 'Documentation and title clarity were excellent.' },
        ],
        languageSupport: ['English', 'Malayalam'],
        disputeCount: 0,
      },
      {
        id: 're-6',
        title: 'Azure Heights Project Launch',
        price: '72 Lakhs onwards',
        priceLabel: '72 Lakhs onwards',
        priceValue: 72,
        area: '1380 sq ft',
        areaSqft: 1380,
        location: 'Kochi',
        locality: 'Edappally',
        type: 'Flat',
        intent: 'project',
        image: 'Project launch',
        bedrooms: 3,
        bathrooms: 2,
        furnishing: 'Semi Furnished',
        amenities: ['Swimming pool', 'Gym', "Children's park", 'EV charging'],
        sellerName: 'West Coast Builders',
        sellerRole: 'Builder',
        developer: 'West Coast Builders',
        listedBy: 'Builder',
        verified: true,
        verificationStatus: 'Verified',
        featured: true,
        postedOn: '2026-04-20',
        possession: 'Dec 2027',
        description: 'A newly launched apartment project with phased inventory management, pre-launch pricing, and digital brochure access.',
        mapLabel: 'Edappally metro growth corridor',
        rating: 4.7,
        reviewCount: 27,
        premiumPlan: 'Featured Listing',
        mediaCount: 15,
        hasVideoTour: true,
        projectUnits: 84,
        leads: [
          { name: 'Haritha', channel: 'Enquiry', priority: 'Hot' },
          { name: 'Manu', channel: 'Chat', priority: 'Warm' },
        ],
        chatPreview: [
          { from: 'West Coast Builders', text: 'Inventory blocks A and B are now open for early booking.' },
        ],
        reviews: [
          { author: 'Home buyer', score: 5, comment: 'Builder team shared plans and payment schedule clearly.' },
        ],
        languageSupport: ['English', 'Malayalam', 'Tamil', 'Hindi'],
        disputeCount: 0,
      },
    ],
    restaurants: [
      { id: 1, name: 'Spice Kitchen', cuisine: 'Indian', rating: 4.5, deliveryTime: '30 mins', image: 'Meals', discount: '20%' },
      { id: 2, name: 'Burger Haven', cuisine: 'Fast Food', rating: 4.2, deliveryTime: '25 mins', image: 'Burger', discount: '10%' },
      { id: 3, name: 'Pasta Paradise', cuisine: 'Italian', rating: 4.6, deliveryTime: '35 mins', image: 'Pasta', discount: '15%' },
      { id: 4, name: 'Sushi Corner', cuisine: 'Japanese', rating: 4.4, deliveryTime: '40 mins', image: 'Sushi', discount: '25%' },
      { id: 5, name: 'Dessert Cafe', cuisine: 'Desserts', rating: 4.7, deliveryTime: '20 mins', image: 'Dessert', discount: '5%' },
    ],
    rideOffers: [
      { id: 1, type: 'MalaRide Economy', pricePerKm: 7, capacity: 4, icon: 'Car', eta: '2 mins' },
      { id: 2, type: 'MalaRide Premium', pricePerKm: 12, capacity: 4, icon: 'Sedan', eta: '3 mins' },
      { id: 3, type: 'MalaRide XL', pricePerKm: 15, capacity: 6, icon: 'Van', eta: '5 mins' },
      { id: 4, type: 'MalaBike', pricePerKm: 5, capacity: 1, icon: 'Bike', eta: '1 min' },
    ],
    conversations: [
      { id: 1, name: 'Rajesh Kumar', lastMessage: 'Thanks for the product! Really happy with it', timestamp: '10:30 AM', unread: true, avatar: 'RK' },
      { id: 2, name: 'Priya Singh', lastMessage: 'When can you deliver?', timestamp: '9:15 AM', unread: false, avatar: 'PS' },
      { id: 3, name: 'Support Team', lastMessage: 'Your order is confirmed', timestamp: 'Yesterday', unread: false, avatar: 'ST' },
    ],
    matrimonialProfiles: [
      { id: 1, name: 'Anjali Sharma', age: 28, religion: 'Hindu', caste: 'Brahmin', location: 'Bangalore', profession: 'Software Engineer', image: 'AS', verified: true, bio: 'Loves reading, traveling, and cooking' },
      { id: 2, name: 'Kavya Singh', age: 26, religion: 'Hindu', caste: 'Kshatriya', location: 'Delhi', profession: 'Doctor', image: 'KS', verified: true, bio: 'Passionate about health and fitness' },
      { id: 3, name: 'Sneha Patel', age: 27, religion: 'Hindu', caste: 'Patel', location: 'Mumbai', profession: 'Lawyer', image: 'SP', verified: true, bio: 'Career-focused, looking for same-minded partner' },
      { id: 4, name: 'Priya Reddy', age: 25, religion: 'Hindu', caste: 'Reddy', location: 'Hyderabad', profession: 'Architect', image: 'PR', verified: true, bio: 'Creative person with passion for design' },
      { id: 5, name: 'Divya Nair', age: 29, religion: 'Hindu', caste: 'Nair', location: 'Kochi', profession: 'Accountant', image: 'DN', verified: true, bio: 'Family-oriented, values traditional values' },
    ],
    socialMediaPosts: [
      { id: 1, author: 'Rajesh Kumar', avatar: 'RK', content: 'Just launched my new product! Excited about this journey.', image: 'Launch', likes: 234, comments: 45, timestamp: '2 hours ago', liked: false },
      { id: 2, author: 'Priya Singh', avatar: 'PS', content: 'Beautiful sunset at the beach! Nature is amazing.', image: 'Beach', likes: 567, comments: 89, timestamp: '4 hours ago', liked: false },
      { id: 3, author: 'Arjun Patel', avatar: 'AP', content: 'Travelled to Paris! Living the dream.', image: 'Travel', likes: 892, comments: 156, timestamp: '1 day ago', liked: false },
      { id: 4, author: 'Neha Sharma', avatar: 'NS', content: 'Coffee and books - the perfect combo.', image: 'Coffee', likes: 445, comments: 78, timestamp: '2 days ago', liked: false },
      { id: 5, author: 'Vikram Singh', avatar: 'VS', content: 'Fitness journey update: 30 days of consistent workouts!', image: 'Fitness', likes: 612, comments: 134, timestamp: '3 days ago', liked: false },
    ],
    socialMediaStories: [
      { id: 1, name: 'Rajesh Kumar', avatar: 'RK', storyCount: 3 },
      { id: 2, name: 'Priya Singh', avatar: 'PS', storyCount: 2 },
      { id: 3, name: 'Arjun Patel', avatar: 'AP', storyCount: 5 },
      { id: 4, name: 'Neha Sharma', avatar: 'NS', storyCount: 1 },
    ],
  },
};

module.exports = {
  DEFAULT_APP_DATA,
  DEFAULT_BUSINESS_CATEGORIES,
};
