export const MODULE_PATHS = {
  dashboard: "/dashboard",
  "admin-dashboard": "/admin-dashboard",
  ecommerce: "/ecommerce",
  cart: "/cart",
  orders: "/orders",
  returns: "/returns",
  messaging: "/messaging",
  classifieds: "/classifieds",
  realestate: "/realestate",
  finance: "/finance",
  freelancer: "/freelancer",
  billpay: "/billpay",
  businessbuilder: "/business-builder",
  nilaaihub: "/nila-ai-hub",
  kidsstoryvideomaker: "/kids-story-video-maker",
  promptvideogenerator: "/prompt-video-generator",
  gulfservices: "/gulf-services",
  hotelbooking: "/hotelbooking",
  healthcare: "/healthcare",
  bustrainbooking: "/bustrainbooking",
  resumebuilder: "/resumebuilder",
  photostudio: "/photo-studio-ai-ar",
  karaokeduet: "/remote-karaoke-duet",
  danceduet: "/dance-duet",
  voicefriend: "/voice-friend",
  liveplaceexplorer: "/live-place-explorer",
  beautyai: "/nila-beauty-ai",
  kitchen: "/smart-kitchen-recipe-hub",
  aibusinessos: "/ai-business-os",
  gulfjobsmigration: "/kerala-gulf-jobs-migration",
  womensafetyfamily: "/women-safety-family-protection",
  devotionalecosystem: "/devotional-ecosystem",
  hyperlocalaicommerce: "/hyperlocal-ai-commerce",
  nilaaistudio: "/nila-ai-studio",
  trustlayer: "/trust-layer",
  businessservices: "/businessservices",
  jobportal: "/jobportal",
  education: "/education",
  tourism: "/tourism",
  skilllearning: "/skilllearning",
  fooddelivery: "/fooddelivery",
  devadarshan: "/devadarshan",
  hyperlocal: "/hyperlocal",
  localservices: "/localservices",
  localmarket: "/localmarket",
  ridesharing: "/ridesharing",
  maps: "/maps",
  matrimonial: "/matrimonial",
  socialmedia: "/socialmedia",
  reminderalert: "/reminderalert",
  quicklinks: "/quicklinks",
  diary: "/diary",
  sosalert: "/sosalert",
  astrology: "/astrology",
  support: "/support",
};

const MODULE_ID_ALIASES = {
  quicklink: "quicklinks",
  "quick-links": "quicklinks",
  mydiary: "diary",
  personaldiary: "diary",
  map: "maps",
  loans: "finance",
  financehub: "finance",
  freelancers: "freelancer",
  worklink: "freelancer",
  nilaworks: "freelancer",
  proconnect: "freelancer",
  skillhub: "skilllearning",
  skills: "skilllearning",
  learning: "skilllearning",
  skillearning: "skilllearning",
  careerhub: "skilllearning",
  utility: "billpay",
  utilities: "billpay",
  bbps: "billpay",
  billpayment: "billpay",
  utilityhub: "billpay",
  hyperlocaldelivery: "hyperlocal",
  "hyperlocal-delivery": "hyperlocal",
  deliveryhub: "hyperlocal",
  instamart: "hyperlocal",
  dunzo: "hyperlocal",
  templebooking: "devadarshan",
  eventbooking: "devadarshan",
  hallbooking: "devadarshan",
  vazhipadu: "devadarshan",
  poojalink: "devadarshan",
  blessinghub: "devadarshan",
  localservice: "localservices",
  "gulf-services": "gulfservices",
  "photo-studio-ai-ar": "photostudio",
  photostudioaiar: "photostudio",
  photostudio: "photostudio",
  aiarstudio: "photostudio",
  "remote-karaoke-duet": "karaokeduet",
  karaokeduet: "karaokeduet",
  karaoke: "karaokeduet",
  duet: "karaokeduet",
  "dance-duet": "danceduet",
  "ai-dance-duet": "danceduet",
  voicefriend: "voicefriend",
  "voice-friend": "voicefriend",
  "ai-voice-friend": "voicefriend",
  liveplace: "liveplaceexplorer",
  "live-place": "liveplaceexplorer",
  "live-place-explorer": "liveplaceexplorer",
  placeexplorer: "liveplaceexplorer",
  "place-explorer": "liveplaceexplorer",
  "nila-beauty-ai": "beautyai",
  "nila-beauty": "beautyai",
  beautyai: "beautyai",
  beauty: "beautyai",
  glowmate: "beautyai",
  "smart-kitchen-recipe-hub": "kitchen",
  smartkitchen: "kitchen",
  kitchen: "kitchen",
  recipes: "kitchen",
  "recipe-hub": "kitchen",
  "ai-business-os": "aibusinessos",
  businessos: "aibusinessos",
  "ai-business-operating-system": "aibusinessos",
  "kerala-gulf-jobs-migration": "gulfjobsmigration",
  gulfjobs: "gulfjobsmigration",
  migration: "gulfjobsmigration",
  "women-safety-family-protection": "womensafetyfamily",
  womensafety: "womensafetyfamily",
  familysafety: "womensafetyfamily",
  "devotional-ecosystem": "devotionalecosystem",
  devotional: "devotionalecosystem",
  templeecosystem: "devotionalecosystem",
  "hyperlocal-ai-commerce": "hyperlocalaicommerce",
  hyperlocalaicommerce: "hyperlocalaicommerce",
  "nila-ai-studio": "nilaaistudio",
  aistudio: "nilaaistudio",
  "trust-layer": "trustlayer",
  trust: "trustlayer",
  gulfservice: "gulfservices",
  gulfservices: "gulfservices",
  "nila-ai-hub": "nilaaihub",
  nilaai: "nilaaihub",
  aiassistant: "nilaaihub",
  ai: "nilaaihub",
  nilahub: "nilaaihub",
  danceduet: "danceduet",
  nilakids: "kidsstoryvideomaker",
  "nila-kids": "kidsstoryvideomaker",
  kidsstory: "kidsstoryvideomaker",
  "kids-video": "kidsstoryvideomaker",
  "prompt-video-generator": "promptvideogenerator",
  promptvideo: "promptvideogenerator",
  "prompt-video": "promptvideogenerator",
  videoprompt: "promptvideogenerator",
  "ai-video-generator": "promptvideogenerator",
  tourismmarketplace: "tourism",
  tourismhub: "tourism",
  travel: "tourism",
  travelhub: "tourism",
  nilatravel: "tourism",
  localservicesmarket: "localservices",
  eventservice: "localservices",
  caterers: "localservices",
  decorators: "localservices",
  photographers: "localservices",
  "business-builder": "businessbuilder",
  homesphere: "realestate",
  homosphere: "realestate",
  "home-sphere": "realestate",
};

export const normalizeModuleId = (moduleId = "") => {
  const normalizedId = String(moduleId || "").trim().toLowerCase();
  return MODULE_ID_ALIASES[normalizedId] || normalizedId;
};

export const ROUTABLE_MODULES = new Set(Object.keys(MODULE_PATHS));

export const getProtectedModuleFromPathname = (pathname = "") =>
  normalizeModuleId(
    String(pathname)
    .split("/")
    .filter(Boolean)[0] || ""
  );

export const getPathForModule = (moduleId = "", fallbackPath = MODULE_PATHS.dashboard) =>
  MODULE_PATHS[normalizeModuleId(moduleId)] || fallbackPath;
